services:
  dspace-cli:
    image: dspace/dspace-cli:dspace-${DSPACE_VERSION}
    env_file:
      - secrets.env
      - dspace.service.env
    entrypoint: /dspace/bin/dspace
    command: help
    tty: true
    stdin_open: true
    volumes:
      - ${DSPACE_ASSET_STORE_HOST_DIR}:/dspace/assetstore:rw
      - ${DSPACE_LOGS_HOST_DIR}:/dspace/logs:rw
networks:
  default:
    name: dspace_dspace-net
    external: true
